
services:
  backend:
      build: .
      container_name: node_backend
      command: npm run start
      restart: always
      ports:
        - "3000:3000"
      volumes:
        - .:/server.js:/app/server.js
      depends_on:
        - db
      environment:
        # DATABASE_URL: "mongodb://mongodb:27017/mydatabase"
        REDIS_HOST: redis
        REDIS_PORT: 6379
      extra_hosts:
        - "localhost:host-gateway"

  db:
        image: postgres:latest
        restart: always
        container_name: postgresdb_container
        environment:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test
        ports:
          - "5432:5432"
        volumes:
          - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis
    container_name: redis_service
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data


volumes:
  # mongo_data:
  postgres_data:
  redis_data:
    driver: local
